title: Herbert Daniel Ludowieg
logo: /assets/img/phd-with-bull-crop.jpg
description: Personal website
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
markdown: kramdown
use-mathjax: true
